allCountryDataMap = {
    "France":{"colorToUse": "dodgerblue"},
    "Germany":{"colorToUse": "orange"},
    "Italy":{"colorToUse": "grey"},
    "United_Kingdom":{"colorToUse": "turquoise"},
    "India":{"colorToUse": "green"},
    "US":{"colorToUse": "red"},
    "Brazil":{"colorToUse": "darkkhaki"},
    "Turkey":{"colorToUse": "coral"},
    "South_Africa":{"colorToUse": "#008B8B"},
    "Spain":{"colorToUse": "#B8860B"},
    "Sri_Lanka":{"colorToUse": "#556B2F"},
    "Russia":{"colorToUse": "#B22222"},
    "New_Zealand":{"colorToUse": "#CD5C5C"},
    "South_Korea":{"colorToUse": "#CD5C5C"},
    "Belarus":{"colorToUse": "#663399"},
    "Iceland":{"colorToUse": "#90EE90"},
    "Japan":{"colorToUse": "#FFA07A"},
    "Latvia":{"colorToUse": "#87CEFA"},
    "Malawi":{"colorToUse": "#32CD32"},
    "Sweden":{"colorToUse": "#C71585"},
    "Taiwan":{"colorToUse": "#6B8E23"},
    "Uruguay":{"colorToUse": "#DA70D6"}
}